### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mlwbd** [Alexmoons/gdshareM#1]
you beutify this, but i need code which include column of drive links like the original one. please

**Comment by Alexmoons** [comment]
with Indonesian translation or English?, if English, you can find it on Github

**Comment by mlwbd** [comment]
With Indonesian, I like the dark theme but missed the drive link column

**Comment by Alexmoons** [comment]
> With Indonesian, I like the dark theme but missed the drive link column

Done

**Comment by mlwbd** [comment]
Thanks will try ..
